const desafios = {
  hetero: [
    "Beije meu corpo inteiro sem encostar nos lábios",
    "Me vende e faça o que quiser por 3 minutos",
    "Me mande um áudio gemendo como se estivesse gozando",
    "Faça uma massagem erótica e termine do jeito que eu pedir",
    "Morda levemente meu pescoço até eu arrepiar",
    "Me beije como se fosse a primeira vez",
    "Me beije em 5 lugares diferentes do corpo",
    "Me dê um beijo molhado de 1 minuto",
    "Me beije de olhos vendados",
    "Me dê um beijo que me deixe com tesão instantâneo",
    "Tire uma peça de roupa minha com a boca",
    "Lamba meus mamilos até eu gemer",
    "Simule um oral em mim por 30 segundos",
    "Sussurre no meu ouvido o que faria se eu estivesse amarrado(a)",
    "Passe um cubo de gelo em todo o meu corpo",
    "Me provoque e pare antes que eu goze",
    "Me faça gemer sem usar as mãos",
    "Dance no meu colo até eu ficar excitado(a)",
    "Me faça um strip-tease lento",
    "Me obrigue a obedecer uma ordem sexual sua",
    "Me faça gozar em menos de 5 minutos",
    "Me toque até eu implorar por mais",
    "Me chupe sem parar até eu pedir para você parar",
    "Me faça perder o fôlego com beijos e mordidas",
    "Me faça gemer alto mesmo tentando segurar",
    "Me amarre e me use como quiser",
    "Me chame por um apelido safado",
    "Me dê tapas na bunda até eu pedir mais",
    "Lamba meu corpo como se fosse um doce",
    "Me deixe no controle do vibrador por 10 minutos",
    "Me faça chegar perto de gozar e pare",
    "Me provoque com a boca sem deixar eu gozar",
    "Use um vibrador em mim, mas só quando eu pedir",
    "Me faça implorar antes de me penetrar",
    "Me deixe esperando sem gozar até o próximo desafio",
    "Me alimente na boca com algo doce e depois me beije",
    "Escreva algo safado no meu corpo com chantilly",
    "Lamba algo do meu corpo até sumir",
    "Me faça rir e depois gozar",
    "Me conte uma fantasia enquanto me toca",
    "Me faça gozar duas vezes seguidas",
    "Me penetre em uma posição diferente",
    "Me chupe até eu não aguentar mais",
    "Me faça gozar sem encostar no genital",
    "Me use como se fosse sua(o) submisso(a)",
    "Me diga como você gostaria que eu te chupasse e depois faça",
    "Me faça gozar primeiro e depois se satisfaça",
    "Me penetre sem pressa, devagar, até eu enlouquecer",
    "Me faça um oral como se fosse o último da vida",
    "Me dê o orgasmo mais intenso que já tive",
    "Beije o pescoço do parceiro(a) por 1 minuto",
    "Faça uma massagem sensual por 5 minutos",
    "Sussurre algo que você deseja fazer hoje",
    "Tire minha roupa usando só a boca",
    "Recriem a primeira vez juntos com mais intensidade",
    "Dança sensual e provocante por uma música inteira",
    "Troquem elogios quentes e excitantes por 2 minutos",
    "Beijo demorado e intenso sem usar as mãos",
    "Explore todo o corpo do outro vendado",
    "Escolha onde tocar e provocar por 1 minuto",
    "Me masturbe olhando nos meus olhos",
    "Faça sexo oral intenso até eu gozar",
    "Me domine completamente por 5 minutos",
    "Sussurre palavrões safados no meu ouvido enquanto me toca",
    "Me penetre forte e devagar alternando o ritmo",
    "Deixe eu gozar na sua boca",
    "Me faça gritar de prazer",
    "Experimente uma nova posição que sempre quis tentar",
    "Me chupe o pescoço enquanto me masturba",
    "Faça amor comigo de forma intensa e apaixonada",
    "Me beije por todo o corpo antes de me penetrar",
    "Use a língua para me deixar louco(a)",
    "Me foda contra a parede",
    "Deixe eu cavalgar no seu colo até gozar",
    "Me provoque com dedos e língua ao mesmo tempo",
    "Gema alto enquanto transamos",
    "Me mostre como você gosta de ser tocado(a)",
    "Faça sexo anal com muito lubrificante e carinho",
    "Me morda com desejo durante o sexo",
    "Grave um vídeo fazendo algo safado para mim",
    "Masturbe-se na minha frente até gozar",
    "Me peça para fazer algo que nunca pediu antes",
    "Transe comigo em um lugar diferente da casa",
    "Me faça um boquete/chupe minha buceta por 10 minutos",
    "Coloque lingerie sexy e se exiba para mim",
    "Me provoque até eu te suplicar para transar",
    "Experimente usar algemas ou vendas",
    "Faça 69 comigo até ambos gozarem",
    "Me penetre enquanto uso um vibrador no clitóris",
    "Faça sexo bem molhado com muito lubrificante",
    "Me deixe te cavalgar enquanto você me puxa o cabelo",
    "Pratique sexo tântrico por 20 minutos sem gozar",
    "Me dedilhe com força até eu gozar gritando",
    "Chupe meu pau/buceta como se estivesse com fome",
    "Transe comigo olhando no espelho",
    "Me foda de quatro bem forte",
    "Experimente dupla penetração com brinquedos",
    "Me faça vir múltiplas vezes seguidas",
    "Pratique edging - pare quando eu estiver quase gozando",
    "Me trate como sua putinha(o) durante o sexo",
    "Goze na minha cara/corpo onde eu mandar",
    "Me faça esguichar de prazer"
  ],
  gay: [
    "Beijo intenso e dominante contra a parede",
    "Massagem com óleo quente em todo o corpo",
    "Descreva sua fantasia favorita em detalhes",
    "Beijo lento começando no peito descendo",
    "Dança provocante no colo dele",
    "Sussurre algo proibido no ouvido dele",
    "Explorem o corpo um do outro sem pressa",
    "Escolha a próxima posição e domine",
    "Beijo sem parar por 2 minutos com língua",
    "Toque onde ele mais gosta até ele gemer",
    "Chupe o pescoço dele até deixar marca",
    "Masturbe ele olhando nos olhos",
    "Faça um boquete lento e sensual",
    "Dedilhe ele até o orgasmo",
    "Me penetre devagar até o fundo",
    "Deixe eu chupar você até gozar",
    "Me foda de quatro com força",
    "Pratique 69 intenso",
    "Me domine completamente",
    "Gema alto enquanto me penetra",
    "Chupe meu pau como se fosse um sorvete",
    "Me beije enquanto me masturba",
    "Experimente uma posição nova",
    "Me amarre e use como quiser",
    "Dê tapas na minha bunda enquanto me fode",
    "Me faça seu submisso por 10 minutos",
    "Frotage - esfregue nossos paus juntos até gozar",
    "Me chupe até eu não aguentar mais",
    "Penetre meu dedo enquanto me chupa",
    "Me faça gozar duas vezes seguidas",
    "Sexo oral mútuo até ambos gozarem",
    "Me trate como sua putinha",
    "Goze na minha boca",
    "Me foda bem forte e rápido",
    "Experimente usar plug anal durante sexo oral",
    "Me penetre enquanto me masturba",
    "Cavalga no meu pau até gozar",
    "Me chupe as bolas enquanto me masturba",
    "Faça rimming em mim",
    "Me penetre contra a parede",
    "Use lubrificante e vá fundo",
    "Me faça gozar sem tocar no meu pau",
    "Experimente dupla penetração com brinquedos",
    "Me deixe gozar dentro de você",
    "Pratique edging - pare antes de eu gozar",
    "Me masturbe com as duas mãos",
    "Chupe meu pau até a garganta",
    "Me penetre em uma posição diferente",
    "Transe comigo no chuveiro",
    "Me morda enquanto transamos",
    "Puxa meu cabelo enquanto me fode",
    "Me faça gritar seu nome",
    "Experimente usar algemas",
    "Sexo tântrico sem ejacular por 20 minutos",
    "Me provoque com a língua por todo o corpo",
    "Goze no meu corpo",
    "Me foda de lado com força",
    "Pratique sexo anal prolongado",
    "Me deixe te cavalgar no controle",
    "Faça amor comigo com intensidade",
    "Me penetre olhando no espelho",
    "Use vibrador em mim enquanto me chupa",
    "Me faça vir múltiplas vezes",
    "Experimente inversão de papéis",
    "Me penetre com força ritmada",
    "Chupe meu pau enquanto me dedilha",
    "Me provoque até eu suplicar",
    "Sexo com muito gemido e palavrões",
    "Me deixe gozar onde eu quiser",
    "Faça um boquete longo e babado",
    "Me penetre sem parar até eu gozar",
    "Experimente posição de colher e foda fundo",
    "Me trate como seu dominador/dominado",
    "Pratique fisting com cuidado e lubrificante",
    "Me faça esguichar de prazer",
    "Goze junto comigo ao mesmo tempo",
    "Me foda até ambos não aguentarem mais",
    "Experimente tantra e orgasmo prolongado",
    "Me mostre quem manda na cama",
    "Faça de tudo que eu pedir sem questionar",
    "Me dê o melhor sexo da minha vida",
    "Gozem juntos de forma intensa",
    "Me penetre até eu perder o controle",
    "Chupe e foda até eu desmaiar de prazer",
    "Seja meu escravo sexual por uma noite",
    "Me faça gozar só com a boca",
    "Experimente sexo rough com consentimento",
    "Me penetre enquanto me beija apaixonadamente",
    "Faça tudo que sempre quis fazer comigo",
    "Me dê múltiplos orgasmos seguidos",
    "Pratique sexo selvagem e intenso",
    "Me deixe te usar como quiser",
    "Goze dentro e continue fodendo",
    "Me faça seu e só seu essa noite",
    "Termine a noite com o melhor orgasmo",
    "Me faça sentir cada centímetro de você",
    "Sexo até o amanhecer sem parar",
    "Me mostre do que você é capaz",
    "Realize minha fantasia mais profunda"
  ],
  safico: [
    "Beijo lento e intenso começando nos lábios",
    "Massagem sensual com as unhas arranhando",
    "Sussurre algo safado que ama nela",
    "Beijo no pescoço até ela arrepiar toda",
    "Dança sensual e provocante juntas",
    "Explorem o toque lentamente por todo corpo",
    "Troquem carícias vendadas",
    "Beijo demorado com mordida leve no lábio",
    "Escolha onde tocar e provocar",
    "Conduza o ritmo da transa por 5 minutos",
    "Chupe os seios dela até ela gemer",
    "Dedilhe ela olhando nos olhos dela",
    "Faça sexo oral até ela gozar",
    "Esfregue suas bucetas juntas (tribadismo)",
    "Use um vibrador nela enquanto a beija",
    "Deixe ela cavalgar no seu rosto",
    "Penetre ela com os dedos com força",
    "Chupe a buceta dela por 10 minutos sem parar",
    "Me deixe chupar sua buceta até você gozar",
    "Faça um 69 intenso e molhado",
    "Me domine e use como quiser",
    "Dê tapas na minha bunda enquanto me dedilha",
    "Me faça gozar múltiplas vezes",
    "Experimente dupla penetração com brinquedos",
    "Chupe meu clitóris enquanto me penetra",
    "Me amarre e me provoque",
    "Use um vibrador em ambas ao mesmo tempo",
    "Me faça esguichar de prazer",
    "Pratique edging - pare quando eu estiver quase gozando",
    "Me penetre com strap-on",
    "Sente no meu rosto e cavalga",
    "Me masturbe enquanto me beija",
    "Experimente anal com plug ou dedos",
    "Faça amor comigo com intensidade",
    "Me chupe toda antes de me penetrar",
    "Use a língua em mim por todo corpo",
    "Me foda com strap-on de quatro",
    "Deixe eu chupar seus dedos depois de me dedilhar",
    "Me provoque com toques leves até eu implorar",
    "Gema alto enquanto transamos",
    "Me mostre como você gosta de ser tocada",
    "Me beije enquanto usa vibrador em mim",
    "Experimente uma posição nova com brinquedos",
    "Me morda com desejo durante o sexo",
    "Masturbe-se na minha frente",
    "Me peça para fazer algo que nunca pediu",
    "Transe comigo em lugar diferente",
    "Me chupe a buceta por 20 minutos",
    "Vista lingerie sexy e se exiba",
    "Me provoque até eu suplicar",
    "Use algemas ou vendas",
    "Pratique 69 até ambas gozarem",
    "Penetre-me enquanto uso vibrador no clitóris",
    "Sexo bem molhado com muito lubrificante",
    "Me deixe cavalgar na sua coxa",
    "Pratique sexo tântrico por 30 minutos",
    "Me dedilhe com força até eu gozar",
    "Chupe minha buceta com fome",
    "Transe comigo no espelho",
    "Me foda de quatro com strap-on",
    "Experimente brinquedos duplos",
    "Me faça vir várias vezes seguidas",
    "Domine-me completamente",
    "Me trate como sua putinha",
    "Goze na minha boca enquanto te chupo",
    "Me faça gemer alto",
    "Esfregue seus seios nos meus",
    "Penetre-me com strap-on contra parede",
    "Use toys em mim simultaneamente",
    "Faça rimming em mim",
    "Me dedilhe por dentro e por fora",
    "Chupe meu clitóris até eu gozar gritando",
    "Me penetre fundo com strap-on grande",
    "Experimente inversão de papéis",
    "Transe comigo no chuveiro",
    "Puxe meu cabelo enquanto me fode",
    "Me faça gritar seu nome",
    "Sexo oral prolongado e intenso",
    "Me provoque com língua por todo corpo",
    "Goze junto comigo usando vibrador",
    "Me foda de lado com strap-on",
    "Me deixe cavalgar você no controle",
    "Faça amor intenso e apaixonado",
    "Use vibrador duplo em nós duas",
    "Me faça ter orgasmos múltiplos",
    "Me penetre olhando no espelho",
    "Chupe enquanto me dedilha forte",
    "Me provoque até eu suplicar mais",
    "Grite e gema durante o sexo",
    "Me deixe gozar quando eu quiser",
    "Chupe minha buceta babando",
    "Me penetre sem parar com strap-on",
    "Experimente fisting com cuidado",
    "Me trate como dominadora/submissa",
    "Me faça ter orgasmo só com dedos",
    "Goze enquanto te penetro",
    "Transe até ambas não aguentarem",
    "Experimente tantra lésbico",
    "Me domine por completo",
    "Faça tudo que eu pedir",
    "Me dê o melhor sexo da vida",
    "Gozem juntas intensamente",
    "Chupe e foda até eu desmaiar",
    "Seja minha escrava sexual hoje",
    "Me penetre com força ritmada"
  ]
};

// duplicando até chegar em 100 sugestões
Object.keys(desafios).forEach(tipo => {
  while (desafios[tipo].length < 100) {
    desafios[tipo].push(...desafios[tipo]);
  }
  desafios[tipo] = desafios[tipo].slice(0, 100);
});

function girar() {
  const botao = document.querySelector('button');
  const resultado = document.getElementById("resultado");
  
  // Adiciona animação
  botao.classList.add('girando');
  resultado.innerText = "🎲 Girando...";
  
  // Após 1 segundo mostra o resultado
  setTimeout(() => {
    const tipo = document.getElementById("tipoCasal").value;
    const lista = desafios[tipo];
    const sorteio = Math.floor(Math.random() * lista.length);
    resultado.innerText = "🔥 " + lista[sorteio];
    botao.classList.remove('girando');
  }, 1000);
}
